/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#00355f',
        'on-primary': '#ffffff',
        'primary-container': '#0f4c81',
        'on-primary-container': '#8ebdf9',
        'inverse-primary': '#a0c9ff',
        secondary: '#855300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea619',
        'on-secondary-container': '#684000',
        'secondary-fixed': '#ffddb8',
        'secondary-fixed-dim': '#ffb95f',
        'on-secondary-fixed': '#2a1700',
        'on-secondary-fixed-variant': '#653e00',
        tertiary: '#003b35',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#00544d',
        'on-tertiary-container': '#5eccbe',
        'tertiary-fixed': '#89f5e7',
        'tertiary-fixed-dim': '#6bd8cb',
        'on-tertiary-fixed': '#00201d',
        'on-tertiary-fixed-variant': '#005049',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        surface: '#f8f9ff',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#42474f',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-tint': '#2d6197',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#727780',
        'outline-variant': '#c2c7d1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'primary-fixed': '#d2e4ff',
        'primary-fixed-dim': '#a0c9ff',
        'on-primary-fixed': '#001c37',
        'on-primary-fixed-variant': '#07497d',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter'],
        'label-sm': ['Inter'],
        'headline-lg-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['Inter'],
        'headline-xl': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
      borderRadius: {
        btn: '8px',
        card: '16px',
        pill: '9999px',
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '2rem',
        'stack-md': '1rem',
        'stack-sm': '0.5rem',
        gutter: '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2.5rem',
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
};
